# note that these values are not used
GSS_C_DELEG_FLAG = 0
GSS_C_MUTUAL_FLAG = 1
GSS_C_REPLAY_FLAG = 2
GSS_C_SEQUENCE_FLAG = 3
GSS_C_CONF_FLAG = 4
GSS_C_INTEG_FLAG = 5
GSS_C_ANON_FLAG = 6
GSS_C_TRANS_FLAG = 7
